browser=chrome
url=https://automationexercise.com/
gmail=ernazarowsuraj@gmail.com
Name=Suroj
LastName=Ernazarov
Address= Kurtdereli sokak doktor apt,Alt?ndag/Ankara
Password=SamsunSport
CompanyName=Baykar